# Generated by Django 3.1.12 on 2021-06-30 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimestampFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('timestampfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.timestampfields')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('done', 'Завершен')], default=1, max_length=20, verbose_name='Статус')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
            bases=('app.timestampfields',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('timestampfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.timestampfields')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.TextField(max_length=200, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
            bases=('app.timestampfields',),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('timestampfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.timestampfields')),
                ('text', models.TextField(max_length=100, verbose_name='Отзыв')),
                ('rating', models.IntegerField(choices=[(1, 'Плохо'), (2, 'Неудовлетворительно'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], default=1, verbose_name='Оценка')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'product-reviews',
                'verbose_name_plural': 'product-reviews',
            },
            bases=('app.timestampfields',),
        ),
        migrations.CreateModel(
            name='ProductPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Товары')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='app.ProductPosition', to='app.Product', verbose_name='Товары'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('timestampfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.timestampfields')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('products', models.ManyToManyField(to='app.Product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
            bases=('app.timestampfields',),
        ),
    ]
